import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import path from "path";
import { fileURLToPath } from 'url';
import { copyFileSync } from 'fs';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const currentDir = path.dirname(fileURLToPath(import.meta.url));
const distDir = `${currentDir}/dist`;

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/closebrackets',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/comment',
		'@codemirror/fold',
		'@codemirror/gutter',
		'@codemirror/highlight',
		'@codemirror/history',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/matchbrackets',
		'@codemirror/panel',
		'@codemirror/rangeset',
		'@codemirror/rectangular-selection',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/stream-parser',
		'@codemirror/text',
		'@codemirror/tooltip',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2016',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${distDir}/main.js`,
};

if (prod) {
	// Production build
	esbuild.build(buildOptions).then(() => {
		copyFileSync(`${currentDir}/manifest.json`, `${distDir}/manifest.json`);
		copyFileSync(`${currentDir}/styles.css`, `${distDir}/styles.css`);
		console.log('✓ Build completed successfully');
	}).catch(() => process.exit(1));
} else {
	// Development build with watch mode
	esbuild.context(buildOptions).then(ctx => {
		ctx.watch();
		copyFileSync(`${currentDir}/manifest.json`, `${distDir}/manifest.json`);
		copyFileSync(`${currentDir}/styles.css`, `${distDir}/styles.css`);
		console.log('👀 Watching for changes...');
	}).catch(() => process.exit(1));
}
